config/routes.rb
Rails.application.routes.draw do
	root 'sales#index'		

	resources :sales,	only: :index
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/sale_iten.rb
class SaleIten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

	def index
		@sales = Sale.all
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaleControls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
	<thead>
	<tr>
		<th>Customer name</th>
		<th>Merchant address</th>
		<th>Merchant name</th>
		<th></th>
	</tr>
	</thead>

	<tbody>
	<% @sales.each do |sale| %>
		<tr>
		<td><%= sale.customer_name %></td>
		<td><%= sale.merchant_address %></td>
		<td><%= sale.merchant_name %></td>
		<td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
	</tbody>
</table>

<br>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>